
INCDIRS = ../..
LIBDIRS = ../..

OCAMLBCFLAGS = -g
OCAMLBLDFLAGS = -g

SOURCES = aiAnko.mli aiAnko.ml
LIBS = libltg
RESULT = aiAnko

BCSUFFIX = _bc
NCSUFFIX = _nc

RESULTDEPS = ../../libltg.cma ../../libltg.cmxa


all: bc nc

include OCamlMakefile
