
INCDIRS = ../..
LIBDIRS = ../..

OCAMLBCFLAGS = -g
OCAMLBLDFLAGS = -g

SOURCES = kamaboko.ml
LIBS = libltg
RESULT = kamaboko

BCSUFFIX = _bc
NCSUFFIX = _nc

RESULTDEPS = ../../libltg.cma ../../libltg.cmxa


all: bc nc

include OCamlMakefile
